#!/usr/bin/env bash
# Remove build outputs written by the comparator run interrupted by the 12:05 bugcheck. All are regenerated by the next run.
cd /home/checker/math/lean/.lake
rm -rf build packages/PrimeNumberTheoremAnd/.lake/build
find packages/mathlib/.lake/build -type f -newermt "2026-10-08 11:57" -name '*.hash' -delete
sync
echo "remaining files newer than 11:57 under .lake: $(find . -type f -newermt '2026-10-08 11:57' | wc -l)"
